app = 'torah-bot'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  PYTHONUNBUFFERED = '1'

[processes]
  app = 'python fly_runner.py'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ["app"] 

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1